data:
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  bipo:
    p: 0.05

model:
  kpr:
    backbone: imagenet_swin_base_patch4_window7_224
    keypoints:
      prompt_masks: keypoints_gaussian
      prompt_preprocess: cck6
    masks:
      dir: "pifpaf_maskrcnn_filtering"
      preprocess: "five_v"
  transreid:
    cam_num: 6
